#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAccessKendoService.Dto
{
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	public partial class ProductDto : IDtoWithKey
	{
		public ProductDto()
		{
		}
		
		public ProductDto(int _productID, string _productName, int? _supplierID, int? _categoryID, string _quantityPerUnit, decimal? _unitPrice, short? _unitsInStock, short? _unitsOnOrder, short? _reorderLevel, bool _discontinued)
		{
			this.ProductID = _productID;
			this.ProductName = _productName;
			this.SupplierID = _supplierID;
			this.CategoryID = _categoryID;
			this.QuantityPerUnit = _quantityPerUnit;
			this.UnitPrice = _unitPrice;
			this.UnitsInStock = _unitsInStock;
			this.UnitsOnOrder = _unitsOnOrder;
			this.ReorderLevel = _reorderLevel;
			this.Discontinued = _discontinued;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int ProductID { get;set; }

		[DataMember]
		public virtual string ProductName { get;set; }

		[DataMember]
		public virtual int? SupplierID { get;set; }

		[DataMember]
		public virtual int? CategoryID { get;set; }

		[DataMember]
		public virtual string QuantityPerUnit { get;set; }

		[DataMember]
		public virtual decimal? UnitPrice { get;set; }

		[DataMember]
		public virtual short? UnitsInStock { get;set; }

		[DataMember]
		public virtual short? UnitsOnOrder { get;set; }

		[DataMember]
		public virtual short? ReorderLevel { get;set; }

		[DataMember]
		public virtual bool Discontinued { get;set; }
	}
}
#pragma warning restore 1591
