#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace OpenAccessKendoService	
{
	public partial class NorthwindContext : OpenAccessContext, INorthwindContextUnitOfWork
	{
		private static string connectionStringName = @"NorthwindConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("Northwind.rlinq");
	
		public NorthwindContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public NorthwindContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public NorthwindContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public NorthwindContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public NorthwindContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Product> Products 
		{
	    	get
	    	{
	        	return this.GetAll<Product>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}

	public interface INorthwindContextUnitOfWork : IUnitOfWork
	{
		IQueryable<Product> Products 
		{ 
			get;
		}
	}
}

namespace OpenAccessKendoService	
{
	public partial class Product
	{
		private int _productID;
		public virtual int ProductID 
		{ 
		    get
		    {
		        return this._productID;
		    }
		    set
		    {
		        this._productID = value;
		    }
		}
		
		private string _productName;
		public virtual string ProductName 
		{ 
		    get
		    {
		        return this._productName;
		    }
		    set
		    {
		        this._productName = value;
		    }
		}
		
		private string _quantityPerUnit;
		public virtual string QuantityPerUnit 
		{ 
		    get
		    {
		        return this._quantityPerUnit;
		    }
		    set
		    {
		        this._quantityPerUnit = value;
		    }
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice 
		{ 
		    get
		    {
		        return this._unitPrice;
		    }
		    set
		    {
		        this._unitPrice = value;
		    }
		}
		
		private short? _unitsInStock;
		public virtual short? UnitsInStock 
		{ 
		    get
		    {
		        return this._unitsInStock;
		    }
		    set
		    {
		        this._unitsInStock = value;
		    }
		}
		
		private short? _unitsOnOrder;
		public virtual short? UnitsOnOrder 
		{ 
		    get
		    {
		        return this._unitsOnOrder;
		    }
		    set
		    {
		        this._unitsOnOrder = value;
		    }
		}
		
		private short? _reorderLevel;
		public virtual short? ReorderLevel 
		{ 
		    get
		    {
		        return this._reorderLevel;
		    }
		    set
		    {
		        this._reorderLevel = value;
		    }
		}
		
		private bool _discontinued;
		public virtual bool Discontinued 
		{ 
		    get
		    {
		        return this._discontinued;
		    }
		    set
		    {
		        this._discontinued = value;
		    }
		}
		
	}
}
#pragma warning restore 1591

